from nagare import ExtrapolationPolicy, LinearInterpolator
from std.collections import List
from std.testing import TestSuite, assert_equal, assert_raises, assert_true


def assert_close(actual: Float64, expected: Float64, tolerance: Float64 = 1e-12) raises:
    assert_true(
        abs(actual - expected) <= tolerance,
        msg=String("expected ", expected, ", got ", actual),
    )


def assert_relative_close(
    actual: Float64, expected: Float64, tolerance: Float64 = 2e-15
) raises:
    var scale = max(abs(expected), 1.0)
    assert_true(
        abs(actual - expected) <= tolerance * scale,
        msg=String("expected ", expected, ", got ", actual),
    )


def assert_finite(value: Float64) raises:
    assert_true(value == value and value - value == 0.0)


def reference_interpolator(
    policy: ExtrapolationPolicy = ExtrapolationPolicy.ERROR,
) raises -> LinearInterpolator:
    # Expected values in this file are independently calculated from the
    # two-point line equation, not generated by another interpolation library.
    return LinearInterpolator(
        [0.0, 0.5, 2.0, 5.0],
        [1.0, 2.0, -1.0, 8.0],
        extrapolation=policy,
    )


def metadata_matches_reference(interpolator: LinearInterpolator) -> Bool:
    """Exercise every metadata accessor from a non-raising function."""
    return (
        interpolator.knot_count() == 4
        and interpolator.domain_start() == 0.0
        and interpolator.domain_end() == 5.0
    )


def test_linear_interpolator_metadata_and_exact_knots() raises:
    var interpolator = reference_interpolator()
    assert_true(metadata_matches_reference(interpolator))
    assert_equal(interpolator.knot_count(), 4)
    assert_equal(interpolator.domain_start(), 0.0)
    assert_equal(interpolator.domain_end(), 5.0)

    assert_equal(interpolator.evaluate(0.0), 1.0)
    assert_equal(interpolator.evaluate(0.5), 2.0)
    assert_equal(interpolator.evaluate(2.0), -1.0)
    assert_equal(interpolator.evaluate(5.0), 8.0)


def test_call_sugar_and_table_accessors() raises:
    var interpolator = reference_interpolator()
    var expected_knots: List[Float64] = [0.0, 0.5, 2.0, 5.0]
    var expected_values: List[Float64] = [1.0, 2.0, -1.0, 8.0]
    var knots = interpolator.knots()
    var values = interpolator.values()
    assert_equal(len(knots), len(expected_knots))
    assert_equal(len(values), len(expected_values))
    for index in range(len(knots)):
        assert_equal(knots[index], expected_knots[index])
        assert_equal(values[index], expected_values[index])

    assert_equal(interpolator(0.25), interpolator.evaluate(0.25))
    var queries: List[Float64] = [0.0, 0.25, 2.0, 5.0]
    var called = interpolator(queries)
    var evaluated = interpolator.evaluate(queries)
    for index in range(len(queries)):
        assert_equal(called[index], evaluated[index])


def test_linear_interpolator_reference_values() raises:
    var interpolator = reference_interpolator()
    assert_close(interpolator.evaluate(0.25), 1.5)
    assert_close(interpolator.evaluate(1.25), 0.5)
    assert_close(interpolator.evaluate(3.0), 2.0)
    assert_close(interpolator.evaluate(4.5), 6.5)


def test_large_finite_ordinates_do_not_overflow_before_division() raises:
    var interpolator = LinearInterpolator([0.0, 4.0], [0.0, 1e308])
    var midpoint = interpolator.evaluate(2.0)
    assert_finite(midpoint)
    assert_relative_close(midpoint, 5e307)


def test_large_opposite_sign_knots_and_values_remain_finite_in_domain() raises:
    var interpolator = LinearInterpolator(
        [-1e308, 1e308],
        [-1e308, 1e308],
    )
    var queries: List[Float64] = [-5e307, 0.0, 5e307]
    for query in queries:
        var value = interpolator.evaluate(query)
        assert_finite(value)
        assert_relative_close(value, query)


def test_default_policy_rejects_extrapolation() raises:
    var interpolator = reference_interpolator()
    with assert_raises(contains="pass extrapolation= to allow this"):
        _ = interpolator.evaluate(-0.1)
    with assert_raises(contains="query 5.1 is outside the knot domain [0.0, 5.0]"):
        _ = interpolator.evaluate(5.1)


def test_clamp_policy_returns_nearest_endpoint() raises:
    var interpolator = reference_interpolator(ExtrapolationPolicy.CLAMP)
    assert_equal(interpolator.evaluate(-100.0), 1.0)
    assert_equal(interpolator.evaluate(100.0), 8.0)


def test_linear_policy_extends_endpoint_segments() raises:
    var interpolator = reference_interpolator(ExtrapolationPolicy.LINEAR)
    assert_close(interpolator.evaluate(-1.0), -1.0)
    assert_close(interpolator.evaluate(6.0), 11.0)


def test_fill_policy_returns_default_nan_or_custom_payload() raises:
    var default_fill = reference_interpolator(ExtrapolationPolicy.FILL)
    assert_true(default_fill.evaluate(-1.0) != default_fill.evaluate(-1.0))
    assert_true(default_fill.evaluate(6.0) != default_fill.evaluate(6.0))
    assert_equal(default_fill.evaluate(0.5), 2.0)

    var custom_fill = reference_interpolator(ExtrapolationPolicy.fill(-1.5))
    assert_equal(custom_fill.evaluate(-1.0), -1.5)
    assert_equal(custom_fill.evaluate(6.0), -1.5)
    assert_equal(custom_fill.evaluate(0.5), 2.0)

    with assert_raises(contains="query must be finite: received nan"):
        _ = custom_fill.evaluate(Float64("nan"))


def test_large_finite_extrapolation_avoids_premature_overflow() raises:
    var descending = LinearInterpolator(
        [0.0, 1.0],
        [1e308, 0.0],
        extrapolation=ExtrapolationPolicy.LINEAR,
    )
    assert_finite(descending.evaluate(2.0))
    assert_relative_close(descending.evaluate(2.0), -1e308)

    var constant = LinearInterpolator(
        [0.0, 1.0],
        [1e308, 1e308],
        extrapolation=ExtrapolationPolicy.LINEAR,
    )
    assert_equal(constant.evaluate(1e308), 1e308)

    var tiny_ordinates = LinearInterpolator(
        [0.0, 1e-308],
        [-1e-308, 1e-308],
        extrapolation=ExtrapolationPolicy.LINEAR,
    )
    assert_finite(tiny_ordinates.evaluate(1.0))
    assert_relative_close(tiny_ordinates.evaluate(1.0), 2.0)


def test_extrapolated_result_uses_signed_infinity_on_overflow() raises:
    var interpolator = LinearInterpolator(
        [0.0, 1.0],
        [0.0, 1e308],
        extrapolation=ExtrapolationPolicy.LINEAR,
    )
    assert_equal(interpolator.evaluate(2.0), Float64("inf"))
    assert_equal(interpolator.evaluate(-2.0), Float64("-inf"))


def test_constructor_rejects_invalid_tables() raises:
    with assert_raises(contains="len(knots) = 2, len(values) = 1"):
        _ = LinearInterpolator([0.0, 1.0], [2.0])
    with assert_raises(contains="knots[1] = 0.0 <= knots[0] = 0.0"):
        _ = LinearInterpolator([0.0, 0.0], [1.0, 2.0])
    with assert_raises(contains="values[1] is nan"):
        _ = LinearInterpolator([0.0, 1.0], [1.0, Float64("nan")])


def test_explicit_validate_rechecks_mutated_tables() raises:
    var valid = reference_interpolator()
    valid.validate()

    var short_knots = reference_interpolator()
    short_knots._knots = [0.0]
    with assert_raises(contains="at least two"):
        short_knots.validate()

    var mismatched_values = reference_interpolator()
    mismatched_values._values = [1.0]
    with assert_raises(contains="equal length"):
        mismatched_values.validate()

    var non_finite_values = reference_interpolator()
    non_finite_values._values[1] = Float64("inf")
    with assert_raises(contains="values must be finite"):
        non_finite_values.validate()

    var duplicate_knots = reference_interpolator()
    duplicate_knots._knots[1] = duplicate_knots._knots[0]
    with assert_raises(contains="strictly increasing"):
        duplicate_knots.validate()

    var non_finite_knots = reference_interpolator()
    non_finite_knots._knots[1] = Float64("nan")
    with assert_raises(contains="knots must be finite"):
        non_finite_knots.validate()


def test_policy_constants_are_distinct() raises:
    assert_true(ExtrapolationPolicy.ERROR != ExtrapolationPolicy.CLAMP)
    assert_true(ExtrapolationPolicy.ERROR != ExtrapolationPolicy.LINEAR)
    assert_true(ExtrapolationPolicy.CLAMP != ExtrapolationPolicy.LINEAR)
    assert_true(ExtrapolationPolicy.FILL != ExtrapolationPolicy.CLAMP)
    assert_true(ExtrapolationPolicy.FILL == ExtrapolationPolicy.FILL)
    assert_true(ExtrapolationPolicy.fill(2.0) == ExtrapolationPolicy.fill(2.0))
    assert_true(ExtrapolationPolicy.fill(2.0) != ExtrapolationPolicy.fill(3.0))
    assert_true(ExtrapolationPolicy.fill(-1.5) != ExtrapolationPolicy.FILL)
    assert_true(ExtrapolationPolicy.fill(Float64("nan")) == ExtrapolationPolicy.FILL)


def test_non_finite_query_is_never_extrapolated() raises:
    var interpolator = reference_interpolator(ExtrapolationPolicy.CLAMP)
    with assert_raises(contains="query must be finite"):
        _ = interpolator.evaluate(Float64("nan"))
    with assert_raises(contains="query must be finite"):
        _ = interpolator.evaluate(Float64("inf"))
    with assert_raises(contains="query must be finite"):
        _ = interpolator.derivative(Float64("nan"))


def test_batch_matches_scalar_for_clamp_and_linear_policies() raises:
    # Fixed, random-ish coverage across both exterior regions, every exact
    # knot, and each interpolation segment.
    var queries: List[Float64] = [
        -3.25,
        -1.0,
        -0.125,
        0.0,
        0.03125,
        0.1,
        0.25,
        0.499,
        0.5,
        0.5001,
        0.75,
        1.125,
        1.5,
        1.999,
        2.0,
        2.001,
        2.25,
        2.75,
        3.125,
        3.5,
        4.0,
        4.5,
        4.875,
        4.999,
        5.0,
        5.001,
        5.5,
        6.75,
        10.0,
        31.0,
    ]
    var clamp = reference_interpolator(ExtrapolationPolicy.CLAMP)
    var clamped = clamp.evaluate(queries)
    assert_equal(len(clamped), len(queries))
    for index in range(len(queries)):
        assert_equal(clamped[index], clamp.evaluate(queries[index]))

    var linear = reference_interpolator(ExtrapolationPolicy.LINEAR)
    var extended = linear.evaluate(queries)
    assert_equal(len(extended), len(queries))
    for index in range(len(queries)):
        assert_equal(extended[index], linear.evaluate(queries[index]))


def test_batch_matches_scalar_for_error_policy_in_domain() raises:
    var queries: List[Float64] = [
        0.0,
        0.03125,
        0.1,
        0.25,
        0.499,
        0.5,
        0.5001,
        0.75,
        1.125,
        1.5,
        1.999,
        2.0,
        2.001,
        2.25,
        2.75,
        3.125,
        3.5,
        4.0,
        4.5,
        4.875,
        4.999,
        5.0,
    ]
    var interpolator = reference_interpolator(ExtrapolationPolicy.ERROR)
    var batch = interpolator.evaluate(queries)
    assert_equal(len(batch), len(queries))
    for index in range(len(queries)):
        assert_equal(batch[index], interpolator.evaluate(queries[index]))


def test_evaluate_into_matches_allocating_wrapper() raises:
    var queries: List[Float64] = [-1.0, 0.0, 0.25, 2.0, 5.0, 6.0]
    var interpolator = reference_interpolator(ExtrapolationPolicy.fill(-1.5))
    var results = List[Float64](length=len(queries), fill=99.0)
    interpolator.evaluate_into(queries, results)

    var allocated = interpolator.evaluate(queries)
    assert_equal(len(results), len(allocated))
    for index in range(len(results)):
        assert_equal(results[index], allocated[index])

    var short_results = List[Float64](length=2, fill=0.0)
    with assert_raises(contains="len(queries) = 6, len(results) = 2"):
        interpolator.evaluate_into(queries, short_results)


def test_batch_derivative_matches_scalar_and_checks_buffer_lengths() raises:
    var queries: List[Float64] = [0.0, 0.25, 2.0, 5.0]
    var interpolator = reference_interpolator()
    var allocated = interpolator.derivative(queries)
    var results = List[Float64](length=len(queries), fill=99.0)
    interpolator.derivative_into(queries, results)
    for index in range(len(queries)):
        assert_equal(allocated[index], interpolator.derivative(queries[index]))
        assert_equal(results[index], allocated[index])

    var short_results = List[Float64](length=1, fill=0.0)
    with assert_raises(
        contains=(
            "query and result buffers must have equal length: "
            "len(queries) = 4, len(results) = 1"
        )
    ):
        interpolator.derivative_into(queries, short_results)


def test_batch_error_policy_rejects_out_of_domain_query() raises:
    var interpolator = reference_interpolator(ExtrapolationPolicy.ERROR)
    var queries: List[Float64] = [0.0, 1.25, 5.001, 2.0]
    with assert_raises(contains="outside the knot domain"):
        _ = interpolator.evaluate(queries)


def test_batch_rejects_non_finite_query_under_every_policy() raises:
    var error = reference_interpolator(ExtrapolationPolicy.ERROR)
    var clamp = reference_interpolator(ExtrapolationPolicy.CLAMP)
    var linear = reference_interpolator(ExtrapolationPolicy.LINEAR)
    var nan_queries: List[Float64] = [0.0, Float64("nan"), 5.0]
    var infinity_queries: List[Float64] = [0.0, Float64("inf"), 5.0]

    with assert_raises(contains="query must be finite"):
        _ = error.evaluate(nan_queries)
    with assert_raises(contains="query must be finite"):
        _ = error.evaluate(infinity_queries)
    with assert_raises(contains="query must be finite"):
        _ = clamp.evaluate(nan_queries)
    with assert_raises(contains="query must be finite"):
        _ = clamp.evaluate(infinity_queries)
    with assert_raises(contains="query must be finite"):
        _ = linear.evaluate(nan_queries)
    with assert_raises(contains="query must be finite"):
        _ = linear.evaluate(infinity_queries)


def test_empty_batch_returns_empty_list() raises:
    var interpolator = reference_interpolator()
    var queries = List[Float64]()
    var batch = interpolator.evaluate(queries)
    assert_equal(len(batch), 0)


def test_affine_data_is_reproduced_across_irregular_intervals() raises:
    var interpolator = LinearInterpolator(
        [-4.0, -0.5, 0.0, 1.25, 8.0],
        [-14.0, -3.5, -2.0, 1.75, 22.0],
    )
    for step in range(97):
        var x = -4.0 + Float64(step) * 0.125
        assert_close(interpolator.evaluate(x), 3.0 * x - 2.0)


def test_full_range_interval_documents_sub_ulp_central_offset() raises:
    var interpolator = LinearInterpolator(
        [-Float64.MAX_FINITE, Float64.MAX_FINITE],
        [-Float64.MAX_FINITE, Float64.MAX_FINITE],
    )
    var value = interpolator.evaluate(1.0)
    assert_finite(value)
    assert_true(value >= -Float64.MAX_FINITE)
    assert_true(value <= Float64.MAX_FINITE)
    # At this condition number, scaling the endpoints maps x=1 below one ULP
    # of the normalized interval. The documented behavior is the finite
    # representable midpoint, not exact recovery of the mathematical offset.
    assert_equal(value, 0.0)


def test_interpolated_value_stays_between_segment_endpoints() raises:
    var interpolator = reference_interpolator()
    var queries: List[Float64] = [0.1, 0.4, 0.75, 1.75, 2.25, 3.5, 4.9]
    for query in queries:
        var value = interpolator.evaluate(query)
        if query < 0.5:
            assert_true(value >= 1.0 and value <= 2.0)
        elif query < 2.0:
            assert_true(value >= -1.0 and value <= 2.0)
        else:
            assert_true(value >= -1.0 and value <= 8.0)


def test_derivative_is_right_continuous_and_follows_policy() raises:
    var interpolator = reference_interpolator()
    assert_close(interpolator.derivative(0.0), 2.0)
    assert_close(interpolator.derivative(0.5), -2.0)
    assert_close(interpolator.derivative(2.0), 3.0)
    assert_close(interpolator.derivative(5.0), 3.0)
    with assert_raises(contains="outside the knot domain"):
        _ = interpolator.derivative(-1.0)

    var clamp = reference_interpolator(ExtrapolationPolicy.CLAMP)
    assert_equal(clamp.derivative(-1.0), 0.0)
    assert_equal(clamp.derivative(6.0), 0.0)
    var linear = reference_interpolator(ExtrapolationPolicy.LINEAR)
    assert_equal(linear.derivative(-1.0), 2.0)
    assert_equal(linear.derivative(6.0), 3.0)
    var fill = reference_interpolator(ExtrapolationPolicy.fill(-7.0))
    assert_equal(fill.derivative(-1.0), -7.0)
    assert_equal(fill.derivative(6.0), -7.0)


def shared_integral_table(
    policy: ExtrapolationPolicy = ExtrapolationPolicy.ERROR,
) raises -> LinearInterpolator:
    return LinearInterpolator(
        [0.0, 1.0, 2.5, 3.0, 4.5, 6.0],
        [0.0, 2.0, 1.0, 3.5, 3.0, 4.0],
        extrapolation=policy,
    )


def test_linear_closed_form_integrals_direction_and_degenerate_ranges() raises:
    var interpolator = shared_integral_table()
    # Exact trapezoid sums, cross-checked against scipy 1.18.0 / numpy 2.5.2.
    assert_close(interpolator.integrate(0.0, 6.0), 14.5)
    assert_close(interpolator.integrate(0.5, 5.5), 12.333333333333332)
    assert_close(
        interpolator.integrate(5.5, 0.5),
        -interpolator.integrate(0.5, 5.5),
    )
    assert_equal(interpolator.integrate(2.5, 2.5), 0.0)
    with assert_raises(contains="integration bounds must be finite"):
        _ = interpolator.integrate(Float64("nan"), 1.0)
    with assert_raises(contains="integration bounds must be finite"):
        _ = interpolator.integrate(0.0, Float64("inf"))


def test_integral_exterior_tails_follow_each_policy() raises:
    with assert_raises(contains="outside the knot domain"):
        _ = shared_integral_table().integrate(-1.0, 6.0)

    # Left endpoint value is zero and right endpoint value is four.
    var clamp = shared_integral_table(ExtrapolationPolicy.CLAMP)
    assert_close(clamp.integrate(-1.0, 7.0), 18.5)

    var default_fill = shared_integral_table(ExtrapolationPolicy.FILL)
    assert_close(default_fill.integrate(0.0, 6.0), 14.5)
    assert_true(default_fill.integrate(-1.0, 6.0) != default_fill.integrate(-1.0, 6.0))
    var zero_fill = shared_integral_table(ExtrapolationPolicy.fill(0.0))
    assert_close(zero_fill.integrate(-1.0, 7.0), 14.5)

    # Linear rays extend the first secant (slope 2) and final secant (slope 2/3).
    var linear = shared_integral_table(ExtrapolationPolicy.LINEAR)
    assert_close(linear.integrate(-1.0, 7.0), 17.833333333333332)


def test_linear_equality_and_writable_shapes() raises:
    var first = shared_integral_table()
    var second = shared_integral_table()
    var clamp = shared_integral_table(ExtrapolationPolicy.CLAMP)
    var first_fill = shared_integral_table(ExtrapolationPolicy.fill(-1.0))
    var second_fill = shared_integral_table(ExtrapolationPolicy.fill(-2.0))
    assert_true(first == second)
    assert_true(first != clamp)
    assert_true(first_fill != second_fill)
    assert_true(
        String(first).startswith(
            "LinearInterpolator(6 knots on [0.0, 6.0], extrapolation=ERROR)"
        )
    )
    assert_equal(String(ExtrapolationPolicy.ERROR), "ERROR")
    assert_equal(String(ExtrapolationPolicy.CLAMP), "CLAMP")
    assert_equal(String(ExtrapolationPolicy.LINEAR), "LINEAR")
    assert_equal(String(ExtrapolationPolicy.FILL), "FILL(value=nan)")
    assert_equal(String(ExtrapolationPolicy.fill(-1.5)), "FILL(value=-1.5)")


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
