from nagare import ExtrapolationPolicy, LinearInterpolator
from std.collections import List
from std.testing import TestSuite, assert_equal, assert_raises, assert_true


def assert_close(actual: Float64, expected: Float64, tolerance: Float64 = 1e-12) raises:
    assert_true(
        abs(actual - expected) <= tolerance,
        msg=String("expected ", expected, ", got ", actual),
    )


def assert_relative_close(
    actual: Float64, expected: Float64, tolerance: Float64 = 2e-15
) raises:
    var scale = max(abs(expected), 1.0)
    assert_true(
        abs(actual - expected) <= tolerance * scale,
        msg=String("expected ", expected, ", got ", actual),
    )


def assert_finite(value: Float64) raises:
    assert_true(value == value and value - value == 0.0)


def reference_interpolator(
    policy: ExtrapolationPolicy = ExtrapolationPolicy.ERROR,
) raises -> LinearInterpolator:
    # Expected values in this file are independently calculated from the
    # two-point line equation, not generated by another interpolation library.
    return LinearInterpolator(
        [0.0, 0.5, 2.0, 5.0],
        [1.0, 2.0, -1.0, 8.0],
        extrapolation=policy,
    )


def test_linear_interpolator_metadata_and_exact_knots() raises:
    var interpolator = reference_interpolator()
    assert_equal(interpolator.knot_count(), 4)
    assert_equal(interpolator.domain_start(), 0.0)
    assert_equal(interpolator.domain_end(), 5.0)

    assert_equal(interpolator.evaluate(0.0), 1.0)
    assert_equal(interpolator.evaluate(0.5), 2.0)
    assert_equal(interpolator.evaluate(2.0), -1.0)
    assert_equal(interpolator.evaluate(5.0), 8.0)


def test_linear_interpolator_reference_values() raises:
    var interpolator = reference_interpolator()
    assert_close(interpolator.evaluate(0.25), 1.5)
    assert_close(interpolator.evaluate(1.25), 0.5)
    assert_close(interpolator.evaluate(3.0), 2.0)
    assert_close(interpolator.evaluate(4.5), 6.5)


def test_large_finite_ordinates_do_not_overflow_before_division() raises:
    var interpolator = LinearInterpolator([0.0, 4.0], [0.0, 1e308])
    var midpoint = interpolator.evaluate(2.0)
    assert_finite(midpoint)
    assert_relative_close(midpoint, 5e307)


def test_large_opposite_sign_knots_and_values_remain_finite_in_domain() raises:
    var interpolator = LinearInterpolator(
        [-1e308, 1e308],
        [-1e308, 1e308],
    )
    var queries: List[Float64] = [-5e307, 0.0, 5e307]
    for query in queries:
        var value = interpolator.evaluate(query)
        assert_finite(value)
        assert_relative_close(value, query)


def test_default_policy_rejects_extrapolation() raises:
    var interpolator = reference_interpolator()
    with assert_raises(contains="outside the knot domain"):
        _ = interpolator.evaluate(-0.1)
    with assert_raises(contains="outside the knot domain"):
        _ = interpolator.evaluate(5.1)


def test_clamp_policy_returns_nearest_endpoint() raises:
    var interpolator = reference_interpolator(ExtrapolationPolicy.CLAMP)
    assert_equal(interpolator.evaluate(-100.0), 1.0)
    assert_equal(interpolator.evaluate(100.0), 8.0)


def test_linear_policy_extends_endpoint_segments() raises:
    var interpolator = reference_interpolator(ExtrapolationPolicy.LINEAR)
    assert_close(interpolator.evaluate(-1.0), -1.0)
    assert_close(interpolator.evaluate(6.0), 11.0)


def test_large_finite_extrapolation_avoids_premature_overflow() raises:
    var descending = LinearInterpolator(
        [0.0, 1.0],
        [1e308, 0.0],
        extrapolation=ExtrapolationPolicy.LINEAR,
    )
    assert_finite(descending.evaluate(2.0))
    assert_relative_close(descending.evaluate(2.0), -1e308)

    var constant = LinearInterpolator(
        [0.0, 1.0],
        [1e308, 1e308],
        extrapolation=ExtrapolationPolicy.LINEAR,
    )
    assert_equal(constant.evaluate(1e308), 1e308)

    var tiny_ordinates = LinearInterpolator(
        [0.0, 1e-308],
        [-1e-308, 1e-308],
        extrapolation=ExtrapolationPolicy.LINEAR,
    )
    assert_finite(tiny_ordinates.evaluate(1.0))
    assert_relative_close(tiny_ordinates.evaluate(1.0), 2.0)


def test_extrapolated_result_uses_signed_infinity_on_overflow() raises:
    var interpolator = LinearInterpolator(
        [0.0, 1.0],
        [0.0, 1e308],
        extrapolation=ExtrapolationPolicy.LINEAR,
    )
    assert_equal(interpolator.evaluate(2.0), Float64("inf"))
    assert_equal(interpolator.evaluate(-2.0), Float64("-inf"))


def test_constructor_rejects_invalid_tables() raises:
    with assert_raises(contains="equal length"):
        _ = LinearInterpolator([0.0, 1.0], [2.0])
    with assert_raises(contains="strictly increasing"):
        _ = LinearInterpolator([0.0, 0.0], [1.0, 2.0])
    with assert_raises(contains="values must be finite"):
        _ = LinearInterpolator([0.0, 1.0], [1.0, Float64("nan")])


def test_mutated_tables_are_revalidated_before_every_public_observation() raises:
    var count_observation = reference_interpolator()
    count_observation._knots = [0.0]
    with assert_raises(contains="at least two"):
        _ = count_observation.knot_count()

    var start_observation = reference_interpolator()
    start_observation._values = [1.0]
    with assert_raises(contains="equal length"):
        _ = start_observation.domain_start()

    var end_observation = reference_interpolator()
    end_observation._values[1] = Float64("inf")
    with assert_raises(contains="values must be finite"):
        _ = end_observation.domain_end()

    var evaluation = reference_interpolator()
    evaluation._knots[1] = evaluation._knots[0]
    with assert_raises(contains="strictly increasing"):
        _ = evaluation.evaluate(0.25)

    evaluation = reference_interpolator()
    evaluation._knots[1] = Float64("nan")
    with assert_raises(contains="knots must be finite"):
        _ = evaluation.evaluate(0.25)


def test_policy_constants_are_distinct_and_typed_construction_is_total() raises:
    assert_true(ExtrapolationPolicy.ERROR != ExtrapolationPolicy.CLAMP)
    assert_true(ExtrapolationPolicy.ERROR != ExtrapolationPolicy.LINEAR)
    assert_true(ExtrapolationPolicy.CLAMP != ExtrapolationPolicy.LINEAR)
    assert_true(ExtrapolationPolicy() == ExtrapolationPolicy.ERROR)
    assert_true(ExtrapolationPolicy(False) == ExtrapolationPolicy.CLAMP)
    assert_true(ExtrapolationPolicy(True) == ExtrapolationPolicy.LINEAR)


def test_every_reachable_policy_mutation_has_defined_semantics() raises:
    var interpolator = reference_interpolator()
    interpolator._extrapolation._extends_linearly = None
    with assert_raises(contains="outside the knot domain"):
        _ = interpolator.evaluate(-1.0)

    interpolator._extrapolation._extends_linearly = False
    assert_equal(interpolator.evaluate(-1.0), 1.0)

    interpolator._extrapolation._extends_linearly = True
    assert_close(interpolator.evaluate(-1.0), -1.0)


def test_non_finite_query_is_never_extrapolated() raises:
    var interpolator = reference_interpolator(ExtrapolationPolicy.CLAMP)
    with assert_raises(contains="query must be finite"):
        _ = interpolator.evaluate(Float64("nan"))
    with assert_raises(contains="query must be finite"):
        _ = interpolator.evaluate(Float64("inf"))


def test_affine_data_is_reproduced_across_irregular_intervals() raises:
    var interpolator = LinearInterpolator(
        [-4.0, -0.5, 0.0, 1.25, 8.0],
        [-14.0, -3.5, -2.0, 1.75, 22.0],
    )
    for step in range(97):
        var x = -4.0 + Float64(step) * 0.125
        assert_close(interpolator.evaluate(x), 3.0 * x - 2.0)


def test_full_range_interval_documents_sub_ulp_central_offset() raises:
    var interpolator = LinearInterpolator(
        [-Float64.MAX_FINITE, Float64.MAX_FINITE],
        [-Float64.MAX_FINITE, Float64.MAX_FINITE],
    )
    var value = interpolator.evaluate(1.0)
    assert_finite(value)
    assert_true(value >= -Float64.MAX_FINITE)
    assert_true(value <= Float64.MAX_FINITE)
    # At this condition number, scaling the endpoints maps x=1 below one ULP
    # of the normalized interval. The documented behavior is the finite
    # representable midpoint, not exact recovery of the mathematical offset.
    assert_equal(value, 0.0)


def test_interpolated_value_stays_between_segment_endpoints() raises:
    var interpolator = reference_interpolator()
    var queries: List[Float64] = [0.1, 0.4, 0.75, 1.75, 2.25, 3.5, 4.9]
    for query in queries:
        var value = interpolator.evaluate(query)
        if query < 0.5:
            assert_true(value >= 1.0 and value <= 2.0)
        elif query < 2.0:
            assert_true(value >= -1.0 and value <= 2.0)
        else:
            assert_true(value >= -1.0 and value <= 8.0)


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
